---
AWSTemplateFormatVersion: 2010-09-09

Description: "Infrastructure for www.thebiggerguy.com"

Parameters:
  GitHash:
    Description: The Git hash used for this deployment
    Type: String

Resources:
  Budget:
    Type: 'AWS::Budgets::Budget'
    DeletionPolicy: Delete
    Properties:
      Budget:
        BudgetName: com-thebiggerguy-www
        BudgetType: COST
        BudgetLimit:
          Amount: 10
          Unit: USD
        TimeUnit: MONTHLY
        CostTypes:
          IncludeTax: true

  DataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: com.thebiggerguy.www
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: s3/
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: project
          Value: com-thebiggerguy-www

  DataBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref DataBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: "CloudFront Read"
            Effect: "Allow"
            Principal:
              AWS: "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E1YON6C0ZCCCYT"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::com.thebiggerguy.www/*"

  LoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: com.thebiggerguy.www-logging
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter # Required for CloudFront logging
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: project
          Value: com-thebiggerguy-www

  LoggingBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
                - /*
            Condition:
              ArnLike:
                'aws:SourceArn': !GetAtt 
                  - DataBucket
                  - Arn
              StringEquals:
                'aws:SourceAccount': !Sub '${AWS::AccountId}'

  CloudFrontMain:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Delete
    Properties:
      DistributionConfig: 
        CNAMEs:
          - www.thebiggerguy.com
        Comment: www.TheBiggerGuy.com
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: True
          ForwardedValues:
            Cookies:
                 Forward: none
            Headers: []
            QueryString: False
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: S3-com.thebiggerguy.www
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: arn:aws:lambda:us-east-1:337154450806:function:cloudfront_s3_index_redirect:6
        DefaultRootObject: index.html
        Enabled: True
        Origins:
          - Id: S3-com.thebiggerguy.www
            DomainName: com.thebiggerguy.www.s3.eu-west-1.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/E1YON6C0ZCCCYT
        PriceClass: PriceClass_100
        # Note:
        # CloudFront is the only AWS service not to support S3 permssions using
        # standard systems. As such manual actions are required.
        # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html
        # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html
        Logging:
          Bucket: !Join [ ".", [ !Ref LoggingBucket, "s3.amazonaws.com" ] ]
          Prefix: cloudfront/
          IncludeCookies: false
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:337154450806:certificate/00c92b51-af3b-4761-a6b6-d0aafc796fb5
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        IPV6Enabled: true
        HttpVersion: http1.1
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
      Tags:
        - Key: project
          Value: com-thebiggerguy-www


Outputs:
  GitHash:
    Description: The Git hash used for this deployment
    Value: !Ref GitHash
