---
AWSTemplateFormatVersion: 2010-09-09

Description: "Infrastructure for www.thebiggerguy.com"

Parameters:
  GitHash:
    Description: The Git hash used for this deployment
    Type: String

Resources:
  Budget:
    Type: 'AWS::Budgets::Budget'
    Properties:
      Budget:
        BudgetName: com-thebiggerguy-www
        BudgetType: COST
        BudgetLimit:
          Amount: 10
          Unit: USD
        TimeUnit: MONTHLY
        CostTypes:
          IncludeTax: true

Outputs:
  GitHash:
    Description: The Git hash used for this deployment
    Value: !Ref GitHash
