#!/usr/bin/env bash

set -o verbose
set -o errexit
set -o pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"

git submodule update --init --recursive

eval "$(cd "${ROOT_DIR}" && python3 -c 'from yaml import load; [print("export {}".format(x)) for x in load(open(".travis.yml", "r"))["env"]["global"]]')"

echo "HUGO_VERSION=${HUGO_VERSION}"
echo "HUGO_HASH=${HUGO_HASH}"

${ROOT_DIR}/.travis/install_hugo.sh "${ROOT_DIR}/.local"

export PATH="${ROOT_DIR}/.local/bin:${PATH}"

hugo ${@}
