#!/usr/bin/env bash

set -o verbose
set -o errexit
set -o pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"

git submodule update --init --recursive

source "${ROOT_DIR}/.ci/versions.sh"

echo "HUGO_VERSION=${HUGO_VERSION}"
echo "HUGO_HASH=${HUGO_HASH}"

${ROOT_DIR}/.ci/install_hugo.sh "${ROOT_DIR}/.local"

export PATH="${ROOT_DIR}/.local/bin:${PATH}"

hugo ${@}
