name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.local
          key: ${{ runner.os }}-${{ hashFiles('.ci/*.sh') }}

      - name: Run Tests
        run: ./.ci/test.sh
        shell: bash

  archive:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Configure Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '^1.11.13'

      - name: Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.local
          key: ${{ runner.os }}-${{ hashFiles('.ci/*.sh') }}

      - name: Archive
        run: ./.ci/archive.sh
        shell: bash

      - name: Determine next version
        id: tag_version
        run: ./.ci/next_tag.sh
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release and tag
        run: |
          gh release create "${{ steps.tag_version.outputs.new_tag }}" \
            public.tar.gz \
            --target "${{ github.sha }}" \
            --title "Release ${{ steps.tag_version.outputs.new_tag }}" \
            --generate-notes
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: archive
    runs-on: ubuntu-22.04
    environment: Deployment
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.local
          key: ${{ runner.os }}-${{ hashFiles('.ci/*.sh') }}

      - name: Assume AWS Role from OIDC
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-1

      - name: Deploy
        run: ./.ci/deploy.sh
        shell: bash
        env:
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
