name: Testing

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.11.13'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: ${{ runner.os }}-${{ hashFiles('.ci/*.sh') }}

      - name: Run Tests
        run: ./.ci/test.sh
        shell: bash
